- task: DockerCompose@0
  inputs:
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: $(AZURE_SUBSCRIPTION)
    azureContainerRegistry: $(AZURE_CONTAINER_REGISTRY)
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'