version: "3.3"
   
services:
  api:
    image: desafiodevopsacr.azurecr.io/desafio-devops:latest
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src
    ports:
      - "8000:8000"